# Generated by Django 4.2 on 2024-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Имя')),
                ('hp', models.PositiveIntegerField(verbose_name='Здоровье')),
                ('attack', models.PositiveIntegerField(verbose_name='Атака')),
                ('speed', models.PositiveIntegerField(verbose_name='Скорость')),
                ('image', models.ImageField(upload_to='characters/', verbose_name='Изображение')),
                ('level', models.CharField(choices=[('0', 'Бесплатный'), ('1', 'Базовый'), ('2', 'Продвинутый'), ('3', 'Премиум')], default='0', max_length=64, null=True, verbose_name='Уровень доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='CharactersAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('access_level', models.CharField(choices=[('0', 'Бесплатный'), ('1', 'Базовый'), ('2', 'Продвинутый'), ('3', 'Премиум')], default='0', max_length=64, null=True, verbose_name='Уровень доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'API ключ персонажей',
                'verbose_name_plural': 'API ключи персонажей',
                'db_table': 'characters_api_keys',
            },
        ),
    ]
