# Generated by Django 4.2 on 2024-07-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
    ]
