# Generated by Django 4.2 on 2024-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_charactersapikey_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersapikey',
            name='on',
        ),
        migrations.AddField(
            model_name='charactersapikey',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Активирован'),
        ),
    ]
