# Generated by Django 4.2 on 2024-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('0', 'Бесплатный'), ('1', 'Базовый'), ('2', 'Продвинутый'), ('3', 'Премиум')], default='0', max_length=64, null=True, verbose_name='Уровень доступа'),
        ),
    ]
